### ISSUE TITLE
The app can crash when changing the WSS link

### ISSUE THREAD

**Issue by babramovitch** [babramovitch/TheButton#1]
When changing the WSS link AWS resets the file permissions.  In the brief instant when I upload to when I set permissions, the app can crash on a users device if it queries for the link.

Need to ensure that the app won't crash, and that it will re-attempt aftewards so it doesn't kill the timer.

**Comment by artganify** [comment]
Hey, it's /u/51314a36596e427a656b from buttonit. ;)

I think the best way to address this problem is updating the uri automatically by parsing /r/button. Since the base of the uri (schema, authority) never changes, I think the easiest way would be making a GET request to the site and reading the incoming stream by hand until the url is found (starting at wss://, ending with "). It doesn't make sense to me to utilize a whole parsing framework or even fetching the complete page.

**Comment by babramovitch** [comment]
Hey :). I've tried loading the site and parsing the link out but not via
the reddit api.

I was loading the site the same way I load the wss link with okhttp but
reddit called me a bot, which I was, and shut it down automatically.  It
would be awesome to find a way to get it directly via their APIs, updating
the link daily can be a pain.

**Comment by babramovitch** [comment]
For the moment I've put a try/catch around it with an alert to the user to try reloading the app in 10 seconds.  This way I'm not causing crashes.  Will look into further on the weekend.

**Comment by babramovitch** [comment]
Added the new header information for my http request, I'm now able to automatically get the items.  To support older users I'll still update the link in the meantime.  I've also set up the old method as a fallback in case something goes wrong with the new code.
